# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_DSPlayer', [dirname(__file__)])
        except ImportError:
            import _DSPlayer
            return _DSPlayer
        if fp is not None:
            try:
                _mod = imp.load_module('_DSPlayer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _DSPlayer = swig_import_helper()
    del swig_import_helper
else:
    import _DSPlayer
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


MAX_SIZE = _DSPlayer.MAX_SIZE
class DSPlayer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DSPlayer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DSPlayer, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _DSPlayer.new_DSPlayer()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _DSPlayer.delete_DSPlayer
    __del__ = lambda self : None;
    def Initialize(self): return _DSPlayer.DSPlayer_Initialize(self)
    def OpenFileDialog(self): return _DSPlayer.DSPlayer_OpenFileDialog(self)
    def DoPlayOrPause(self): return _DSPlayer.DSPlayer_DoPlayOrPause(self)
    def DoStop(self): return _DSPlayer.DSPlayer_DoStop(self)
    def DoPlay(self): return _DSPlayer.DSPlayer_DoPlay(self)
DSPlayer_swigregister = _DSPlayer.DSPlayer_swigregister
DSPlayer_swigregister(DSPlayer)


def CreateDSPlayerObject():
  return _DSPlayer.CreateDSPlayerObject()
CreateDSPlayerObject = _DSPlayer.CreateDSPlayerObject

def DeleteDSPlayerObject(*args):
  return _DSPlayer.DeleteDSPlayerObject(*args)
DeleteDSPlayerObject = _DSPlayer.DeleteDSPlayerObject


